"use client";

// Client-side YouTube cookie extraction after consent opt-in.
// SO 75426272: chrome.cookies.getAll({domain:"youtube.com"}) misses HttpOnly/partitioned;
// correct is getAll({url:"https://www.youtube.com"}) with host_permissions.

export const YT_CONSENT_KEY = "clipzard_youtube_cookie_consent";
export const COOKIE_CONSENT_KEY = "clipzard_cookie_consent";

export function hasYoutubeConsent(): boolean {
  try {
    return localStorage.getItem(YT_CONSENT_KEY) === "1";
  } catch {
    return false;
  }
}

// Try chrome.cookies API (requires extension with "cookies" + host_permissions).
// Returns Netscape format string or null if not available.
export async function getYoutubeCookiesViaExtension(): Promise<string | null> {
  try {
    // @ts-ignore - chrome may be undefined in regular web page
    const chromeAny = (globalThis as any).chrome;
    if (!chromeAny?.cookies?.getAll) return null;
    const cookies: Array<{
      domain: string;
      hostOnly: boolean;
      path: string;
      secure: boolean;
      expirationDate?: number;
      name: string;
      value: string;
    }> = await new Promise((resolve, reject) => {
      chromeAny.cookies.getAll({ url: "https://www.youtube.com" }, (cs: any) => {
        if (chromeAny.runtime?.lastError) reject(new Error(chromeAny.runtime.lastError.message));
        else resolve(cs);
      });
    });
    if (!cookies || cookies.length === 0) return null;
    // Format as Netscape HTTP Cookie File
    const lines = ["# Netscape HTTP Cookie File", "# Generated by ClipZard (client consent)"];
    for (const c of cookies) {
      const domain = c.domain.startsWith(".") ? c.domain : c.domain;
      const flag = c.hostOnly ? "FALSE" : "TRUE";
      const path = c.path;
      const secure = c.secure ? "TRUE" : "FALSE";
      const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
      lines.push([domain, flag, path, secure, String(expiry), c.name, c.value].join("\t"));
    }
    const txt = lines.join("\n");
    // Must contain youtube.com to be valid for yt-dlp
    if (!txt.toLowerCase().includes("youtube.com")) return null;
    return txt;
  } catch {
    return null;
  }
}

// Fallback: read a user-uploaded cookies.txt file (from "Get cookies.txt LOCALLY")
export function readCookiesFile(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result || ""));
    reader.onerror = () => reject(new Error("Failed to read file"));
    reader.readAsText(file);
  });
}

// Unified helper: try sessionStorage (pre-captured after consent), then extension, else null
export async function getClientYoutubeCookies(): Promise<string | null> {
  if (!hasYoutubeConsent()) return null;
  try {
    const cached = sessionStorage.getItem("clipzard_youtube_cookies");
    if (cached && cached.toLowerCase().includes("youtube.com")) return cached;
  } catch {}
  const viaExt = await getYoutubeCookiesViaExtension();
  if (viaExt) {
    try {
      sessionStorage.setItem("clipzard_youtube_cookies", viaExt);
    } catch {}
    return viaExt;
  }
  return null;
}
