"""add captions: timeline_words, caption_styles, clips.caption_json

Revision ID: 53be73d67c77
Revises: f00e384de046
Create Date: 2026-08-21 10:07:54.656634

"""
from __future__ import annotations

import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53be73d67c77'
down_revision: Union[str, None] = 'f00e384de046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_table(conn, name: str) -> bool:
    return conn.dialect.has_table(conn, name)


def _has_column(conn, table: str, col: str) -> bool:
    return any(c["name"] == col for c in sa.inspect(conn).get_columns(table))


def _has_index(conn, table: str, idx: str) -> bool:
    return any(i["name"] == idx for i in sa.inspect(conn).get_indexes(table))


def upgrade() -> None:
    conn = op.get_bind()
    if not _has_table(conn, "caption_styles"):
        op.create_table('caption_styles',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('label', sa.String(), nullable=False),
        sa.Column('config', sa.JSON(), nullable=False),
        sa.Column('is_builtin', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_index(conn, "caption_styles", "ix_caption_styles_key"):
        op.create_index(op.f('ix_caption_styles_key'), 'caption_styles', ['key'], unique=True)
    if not _has_table(conn, "timeline_words"):
        op.create_table('timeline_words',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(), nullable=False),
        sa.Column('idx', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('start_ms', sa.Integer(), nullable=False),
        sa.Column('end_ms', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if not _has_index(conn, "timeline_words", "ix_timeline_words_project_id"):
        op.create_index(op.f('ix_timeline_words_project_id'), 'timeline_words', ['project_id'], unique=False)
    if not _has_column(conn, "clips", "caption_json"):
        op.add_column('clips', sa.Column('caption_json', sa.JSON(), nullable=True))

    _seed_builtin_caption_styles()


def _seed_builtin_caption_styles() -> None:
    """Insert the built-in caption style presets (idempotent via ON CONFLICT)."""
    import json
    import os
    import sys

    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
    from app.caption_presets import BUILTIN_CAPTION_STYLES

    conn = op.get_bind()
    for style in BUILTIN_CAPTION_STYLES:
        conn.execute(
            sa.text(
                """
                INSERT INTO caption_styles (id, key, label, config, is_builtin)
                VALUES (:id, :key, :label, cast(:config as json), true)
                ON CONFLICT (key) DO NOTHING
                """
            ),
            {
                "id": uuid.uuid4().hex,
                "key": style["key"],
                "label": style["label"],
                "config": json.dumps(style["config"]),
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'caption_json')
    op.drop_index(op.f('ix_timeline_words_project_id'), table_name='timeline_words')
    op.drop_table('timeline_words')
    op.drop_index(op.f('ix_caption_styles_key'), table_name='caption_styles')
    op.drop_table('caption_styles')
    # ### end Alembic commands ###
