"""add projects.language

Revision ID: 9d8e0faf72f5
Revises: 53be73d67c77
Create Date: 2026-08-21 11:16:15.350151

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d8e0faf72f5'
down_revision: Union[str, None] = '53be73d67c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    if not any(c["name"] == "language" for c in sa.inspect(conn).get_columns("projects")):
        op.add_column('projects', sa.Column('language', sa.String(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'language')
    # ### end Alembic commands ###
