"""add job type, clip video nullable, project source_key

Revision ID: f00e384de046
Revises: 2c454fc7dab9
Create Date: 2026-08-20 17:27:17.179528

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f00e384de046'
down_revision: Union[str, None] = '2c454fc7dab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clips', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('jobs', sa.Column('type', sa.String(), server_default='analyze', nullable=False))
    op.add_column('jobs', sa.Column('clip_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_jobs_clip_id'), 'jobs', ['clip_id'], unique=False)
    op.add_column('projects', sa.Column('source_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'source_key')
    op.drop_index(op.f('ix_jobs_clip_id'), table_name='jobs')
    op.drop_column('jobs', 'clip_id')
    op.drop_column('jobs', 'type')
    op.alter_column('clips', 'video_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
